/*
 * FieldWork Project debriefing API 
 * This is the set of APIs for managing FieldWork Project Debriefing, including Commercial Opportunities, Approvals, etc.
 *
 * OpenAPI spec version: 0.0.2
 * Contact: dvlapisupport@bhge.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.mava.dto;

import java.time.LocalDateTime;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import org.apache.logging.log4j.util.Strings;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Getter;
import lombok.Setter;

/**
 * System.
 */
@Getter
@Setter
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-08-23T09:15:41.799Z")
public class SystemDTO {

	/** The created by. */
	@JsonProperty("createdBy")
	@NotNull
	@NotBlank
	@NotEmpty
	private String createdBy = Strings.EMPTY;

	/** The created on. */
	@JsonProperty("createdOn")
	@NotNull
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime createdOn = null;

	/** The last updated by. */
	@JsonProperty("lastUpdatedBy")
	@NotNull
	@NotBlank
	@NotEmpty
	private String lastUpdatedBy = Strings.EMPTY;

	/** The last updated on. */
	@JsonProperty("lastUpdatedOn")
	@NotNull
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss")
	private LocalDateTime lastUpdatedOn = null;

	public SystemDTO init(@NotNull @NotBlank @NotEmpty String createdBy, @NotNull LocalDateTime createdOn,
			@NotNull @NotBlank @NotEmpty String lastUpdatedBy, @NotNull LocalDateTime lastUpdatedOn) {
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedOn = lastUpdatedOn;
		return this;
	}

}
